CREATE TABLE `YossiSherry_AllUsers` (
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` datetime,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` datetime,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `YossiSherry_test_female` (
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `YossiSherry_test_male` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;









/*
CREATE TABLE `YossiSherry_Test_1` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `YossiSherry_Test_2` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `YossiSherry_Test_3` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `YossiSherry_Test_4` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `YossiSherry_Test_5` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `YossiSherry_Test_6` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `YossiSherry_Test_7` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `YossiSherry_Test_8` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `YossiSherry_Test_9` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;





CREATE TABLE `YossiSherry_Test_10` 
(
  `gender` text,
  `email` text,
  `phone` text,
  `cell` text,
  `nat` text,
  `name_title` text,
  `name_first` text,
  `name_last` text,
  `location_street_number` bigint(20) DEFAULT NULL,
  `location_street_name` text,
  `location_city` text,
  `location_state` text,
  `location_country` text,
  `location_postcode` text,
  `location_coordinates_latitude` text,
  `location_coordinates_longitude` text,
  `location_timezone_offset` text,
  `location_timezone_description` text,
  `login_uuid` text,
  `login_username` text,
  `login_password` text,
  `login_salt` text,
  `login_md5` text,
  `login_sha1` text,
  `login_sha256` text,
  `dob_date` text,
  `dob_age` bigint(20) DEFAULT NULL,
  `registered_date` text,
  `registered_age` bigint(20) DEFAULT NULL,
  `id_name` text,
  `id_value` text,
  `picture_large` text,
  `picture_medium` text,
  `picture_thumbnail` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
*/
 



